
export const navigations = [
    {
        id: 'ManagementSupport',
        title: 'Management Support',
        translate: 'MANAGEMENT_SUPPORT',
        type: 'collapsable',
        icon: 'manage_accounts',
        iconType: 'material',
        isVisible: true,
        children: [
            // {
            //     id: 'managementsupport.dashboard',
            //     title: 'Dashboard',
            //     translate: 'DASHBOARD',
            //     type: 'item',
            //     // icon: 'dashboard',
            //     // iconType: 'material',
            //     url: '/dashboard',
            //     isVisible: true,
            // },
            // {
            //     id: 'managementsupport.campaign',
            //     title: 'CAMPAIGNS',
            //     translate: 'CAMPAIGNS',
            //     // icon: 'contact_mail',
            //     // iconType: 'material',
            //     type: 'item',
            //     url: '/campaign',
            //     isVisible: true,
            // },
            {
                id: 'ManagementSupport.ProjectModule',
                title: 'APP_ACADEMY_MODULE',
                translate: 'APP_ACADEMY_MODULE',
                type: 'item',
                url: '/academy-module',
                isVisible: true,
            },
            {
                id: 'ManagementSupport.Articles',
                title: 'Articles',
                translate: 'ARTICLES',
                type: 'collapsable',
                // icon: 'group',
                // iconType: 'material',
                isVisible: true,
                children: [
                    {
                        id: 'ManagementSupport.Articles.ArticleList',
                        title: 'Articles',
                        translate: 'ARTICLES',
                        type: 'item',
                        url: 'articles/articleslist',
                        isVisible: true,
                    },
                    {
                        id: 'ManagementSupport.Articles.DescriptionTemplate',
                        title: 'Description Template',
                        translate: 'DESCRIPTION_TEMPLATE',
                        type: 'item',
                        url: '/articles/templates',
                        isVisible: true,
                    },
                    {
                        id: 'ManagementSupport.Articles.DescriptionTemplate',
                        title: 'Email Template',
                        translate: 'EMAIL_TEMPLATES',
                        type: 'item',
                        url: '/articles/emailtemplates',
                        isVisible: true,
                    }
                ],
            },
             {
                id: 'ManagementSupport.EmploymentLocation',
                title: 'Employment Location',
                translate: 'EMPLOYMENT_LOCATION',
                type: 'item',
                url: '/employment-location',
                isVisible: true,
            },
            {
                id: 'ManagementSupport.Dna',
                title: 'DNA',
                translate: 'DNA',
                type: 'item',
                url: '/dna',
                isVisible: true,
            },
            {
                id: 'ManagementSupport.Dna',
                title: 'General Bundle',
                translate: 'GENERAL_BUNDLE',
                type: 'item',
                url: '/general-bundle',
                isVisible: true,
            },
        ],
    },
    {
        id: 'User-Management',
        title: 'User Management',
        translate: 'USER_MANAGEMENT',
        type: 'collapsable',
        icon: 'icon-profile',
        isVisible: true,
        children: [
            {
                id: 'User-Management.IAM',
                title: 'IAM',
                translate: 'IAM',
                type: 'item',
                // icon: 'icon-profile',
                url: '/iam',
                isVisible: true,
            },
            {
                id: 'User-Management.RoleManager',
                title: 'Role Manager',
                translate: 'ROLE_MANAGER',
                type: 'item',
                // icon: 'icon-profile',
                url: '/role-manager',
                isVisible: true,
            },
        ]
    },
    {
        id: 'MADirectory',
        title: 'MA Directory (HR)',
        translate: 'MA_Directory_HR',
        type: 'collapsable',
        icon: 'description',
        iconType: 'material',
        isVisible: true,
        children: [
            {
                id: 'MADirectory.Hiring.HiringProcessEdit',
                title: 'Application Forms',
                translate: 'APPLICATION_FORMS',
                type: 'item',
                url: '/hiring/jobforms',
                isVisible: true,
                children: [],
            },
            {
                id: 'MADirectory.Hiring',
                title: 'Hiring',
                translate: 'HIRING',
                type: 'collapsable',
                isVisible: true,
                children: [
                    {
                        id: 'MADirectory.Hiring.HiringProcess',
                        title: 'Hiring Process',
                        translate: 'HIRING_PROCESS',
                        type: 'item',
                        url: '/hiring/scrumboard',
                        isVisible: true,
                    },
                    {
                        id: 'MADirectory.Hiring.ArchiveList',
                        title: 'Archive List',
                        translate: 'ARCHIVE_LIST',
                        type: 'item',
                        url: '/hiring/archives',
                        isVisible: true,
                    },
                ],
            },
            {
                id: 'MADirectory.Jobs',
                title: 'Jobs',
                translate: 'JOBS',
                type: 'collapsable',
                isVisible: true,
                children: [
                    {
                        id: 'MADirectory.Jobs',
                        title: 'Job List',
                        translate: 'JOB_LIST',
                        type: 'item',
                        url: '/hiring/jobs',
                        isVisible: true,
                    },
                ],
            },
        ],
    },
    {
        id: 'directory',
        title: 'employee directory',
        translate: 'DIRECTORY',
        type: 'item',
        icon: 'import_contacts',
        iconType: 'material',
        url: 'employee',
        isVisible: true,
    },
    {
        id: 'academy',
        title: 'Academy',
        translate: 'ACADEMY',
        type: 'collapsable',
        icon: 'school',
        iconType: 'material',
        isVisible: true,
        children: [
            {
                id: 'Academy.Training',
                title: 'Training',
                translate: 'TRAINING',
                type: 'item',
                // icon: 'school',
                // iconType: 'material',
                url: 'training',
                isVisible: true,
            },
            // {
            //     id: 'academy.courses',
            //     title: 'Courses',
            //     translate: 'COURSES',
            //     type: 'collapsable',
            //     isVisible: true,
            //     children: [
            //         {
            //             id: 'academy.courses.allcourses',
            //             title: 'All Courses',
            //             translate: 'ALL_COURSES',
            //             type: 'item',
            //             url: '/courses',
            //             isVisible: true,
            //         },
            //         {
            //             id: 'academy.courses.mycourses',
            //             title: 'My Courses',
            //             translate: 'MY_COURSES',
            //             type: 'item',
            //             url: '/mycourses',
            //             isVisible: true,
            //         },
            //         {
            //             id: 'academy.courses.courserequest',
            //             title: 'Course Requests',
            //             translate: 'COURSE_REQUESTS',
            //             type: 'item',
            //             url: '/course-requests',
            //             isVisible: true,
            //         },
            //     ]
            // }
        ]
    },
    {
        id: 'Offer',
        title: 'Offers',
        translate: 'OFFERS',
        url: '/offers',
        type: 'item',
        icon: 'icon-write-letter',
        iconType: 'SLIcon',
        isVisible: true,
    },

    {
        id: 'CRM.Lists',
        title: 'CRM',
        translate: 'CRM',
        type: 'collapsable',
        icon: 'web',
        iconType: 'material',
        isVisible: true,
        children: [
            {
                id: 'CRM.Lists.Customers',
                title: 'Customer',
                translate: 'CUSTOMERS',
                type: 'item',
                url: '/crm/customer',
                isVisible: true,
            },
            {
                id: 'CRM.Lists.Partners',
                title: 'Partners',
                translate: 'PARTNERS',
                type: 'item',
                url: '/crm/partners',
                isVisible: true,
            },
            {
                id: 'CRM.Lists.Supplier',
                title: 'Supplier',
                translate: 'SUPPLIERS',
                type: 'item',
                url: '/crm/supplier',
                isVisible: true,
            },
            {
                id: 'CRM.Lists.SubContractor',
                title: 'Subcontractor',
                translate: 'SUBCONTRACTORS',
                type: 'item',
                url: '/crm/subcontractor',
                isVisible: true,
            },
            {
                id: 'CRM.Lists.Friend',
                title: 'Friends',
                translate: 'FRIENDS',
                type: 'item',
                url: '/crm/friends',
                isVisible: true,
            },
        ],
    },
    {
        id: 'Payroll',
        title: 'Payroll',
        translate: 'PAYROLL',
        type: 'collapsable',
        icon: 'payments',
        iconType: 'material',
        isVisible: true,
        children: [
            {
                id: 'Payroll.All-Employees',
                title: 'All Employees',
                translate: 'ALL_EMPLOYEES',
                type: 'item',
                url: 'payroll/all-employee',
                isVisible: true,
            }
        ],
    },

    {
        id: 'Workforce',
        title: 'Workforce (EM)',
        translate: 'Workforce_EM',
        type: 'collapsable',
        icon: 'icon-projects',
        isVisible: true,
        children: [
            {
                id: 'Workforce.Planning',
                title: 'Planning2',
                translate: 'PLANNING',
                type: 'item',
                url: '/planning-proj',
                isVisible: true,
            },
            {
                id: 'Workforce.Planning',
                title: 'OpenPositions',
                translate: 'OPEN_POSITIONS',
                type: 'item',
                url: '/open-positions',
                isVisible: true,
            },
            {
                id: 'Workforce.OnsiteLeader',
                title: 'OnsiteLeader',
                translate: 'ONSITE_LEADER_INSTRUCTOR',
                type: 'item',
                url: '/onsite-leader',
                isVisible: true,
            },
            {
                id: 'Workforce.EmployeeSchedule',
                title: 'Employee Schedule',
                translate: 'EMPLOYEE_SCHEDULE',
                type: 'item',
                url: '/employee-schedule',
                isVisible: true,
            },
            {
                id: 'Workforce.VehiclePlanning',
                title: 'Vehicle Planning',
                translate: 'VEHICLE_PLANNING',
                type: 'item',
                url: '/vehicle-planning',
                isVisible: true,
            },
            {
                id: 'workforce.onsitereport',
                // title: 'Onsite Report2',
                // translate: 'ONSITE_REPORT',
                title: 'REPORTS',
                translate: 'REPORTS',
                type: 'item',
                url: '/onsite-report',
                isVisible: true,
            },
            {
                id: 'Workforce.Call-Center-Report',
                title: 'Emergency Call Center',
                translate: 'EMERGENCY_CALL_CENTER',
                type: 'item',
                url: '/emergency-call-center',
                isVisible: true,
            },
            {
                id: 'Workforce.Refund',
                title: 'Refund List',
                translate: 'REFUND_LIST',
                type: 'item',
                url: '/refund',
                isVisible: true,
            },
            {
                id: 'Workforce.Workhour',
                title: 'Work Hour',
                translate: 'WORK_HOUR',
                type: 'item',
                url: '/work-hour',
                isVisible: true,
            },
            {
                id: 'workforce.projectsbriefs',
                title: 'Projects & Briefs',
                translate: 'PROJECTS_BRIEFS',
                type: 'item',
                url: '/projects-briefs',
                isVisible: true,
            },
            {
                id: 'Workforce.LeaveRequest.View',
                title: 'Leave Request(s)',
                translate: 'LEAVE_REQUESTS',
                type: 'item',
                url: '/leave-request',
                isVisible: true,
            },
            {
                id: 'Workforce.MyLeaveRequest',
                title: 'My Leave Request(s)',
                translate: 'MY_LEAVE_REQUEST(S)',
                type: 'item',
                url: '/self-leave-request/',
                isVisible: true,
            },
            {
                id: 'Workforce.Taskmanager',
                title: 'Task Manager',
                translate: 'TASK_MANAGER',
                type: 'item',
                // icon: 'table_chart',
                // iconType: 'material',
                url: '/taskmanager',
                isVisible: true,
            }
        ],
    },
    {
        id: 'Invoice',
        title: 'Invoice',
        translate: 'INVOICE',
        type: 'item',
        icon: 'receipt_long',
        iconType: 'material',
        url: 'invoice',
        isVisible: true,
    },
    {
        id: 'Announcement',
        title: 'Announcement',
        translate: 'ANNOUNCEMENT',
        type: 'item',
        icon: 'campaign',
        iconType: 'material',
        url: 'announcement',
        isVisible: true,
    },
    {
        id: 'DMS',
        title: 'DMS',
        translate: 'DMS',
        type: 'collapsable',
        icon: 'folder',
        iconType: 'material',
        isVisible: true,
        children: [
            {        
                id: 'DMS',
                title: 'DMS',
                translate: 'DMS',
                type: 'item',
                icon: 'folder',
                iconType: 'material',
                url: 'dms',
                isVisible: true,
            },
            {
                id: 'DMS',
                title: 'MA_APP',
                translate: 'MA_APP',
                type: 'item',
                icon: 'folder',
                iconType: 'material',
                url: 'organizational-documents',
                isVisible: true,
            },
        ]
    },


    // {
    //     id: 'UserSubscriptionPlan',
    //     title: 'My Subscriptions',
    //     translate: 'MY_SUBSCRIPTIONS',
    //     type: 'item',
    //     url: '/subscriptions/user-subscription-plan',
    //     icon: 'icon-write-letter',
    //     iconType: 'SLIcon',
    //     isVisible: true,
    // },
    {
        id: 'Settings',
        title: 'Settings',
        translate: 'SETTINGS',
        type: 'collapsable',
        icon: 'settings_applications',
        iconType: 'material',
        isVisible: true,
        children: [
            {
                id: 'Settings.HrEmSegmentation',
                url: '/settings',
                title: 'HR/EM Segmentation',
                translate: 'HR_EM_SEGMENTATION_SETTINGS',
                type: 'item',
                isVisible: true,
            },
            {
                id: 'SubscriptionPlans',
                title: 'Subscription Plans',
                translate: 'SUBSCRIPTION_PLANS',
                type: 'item',
                url: '/subscriptions/create-subscription-plan',
                isVisible: true,
            },
            {
                id: 'Settings.MaterialPackage',
                title: 'Material Package',
                translate: 'MATERIAL_PACKAGE',
                type: 'item',
                url: '/material-package',
                isVisible: true,
            },
            {
                id: 'Settings.PricingMaterialBundle',
                title: 'Pricing Material Bundle',
                translate: 'PRICING_MATERIAL_BUNDLE',
                type: 'item',
                url: '/pricing-material-bundle',
                isVisible: true,
            },
        ],
    },
];
